module RgHwCodebreaker
  class Cli
    MENU = { main_menu: %w[start_game best_results help],
             in_game_menu: %w[submit_guess hint go_to_main_menu],
             after_game_menu: %w[play_again go_to_main_menu],
             short_menu: %w[go_to_main_menu] }.freeze
    WELCOME_MSG = "Welcome to CODEBREAKER!\n\n".freeze
    HELP_MSG = "HELP\n\nCodebreaker is a logic game where you will have to "\
               'break a secret code generated by your computer. Secret code '\
               'is a four-digit number where each digit is in the range from '\
               '1 to 6. You have 10 turns to guess. Each turn you have to '\
               "input four digits and system will return you up to four '+' "\
               "and '-' signs. A '+' indicates an exact match: one of the "\
               'digits in the guess is the same as one of the digits in the '\
               "secret code and in the same position. A '-' indicates a "\
               'number match: one of the numbers in the guess is the same as '\
               'one of the numbers in the secret code but in a different '\
               "position.\n\nGood luck!\n\n".freeze
    GAME_MSG = "GAME\n\nSecret code was generated.\nIt is your turn. Choose "\
               "'Submit guess' to make a guess (must include four digits in "\
               "the range from 1 to 6! elsewise it will be rejected).\n\n"\
               'NOTE 1: If you go to main menu or exit your current game will '\
               "be lost.\nNOTE 2: Use hint to open one digit from secret "\
               "code.\n\n".freeze
    INVALID_MSG = "Select valid option to continue!\n\n".freeze
    WIN_MSG = "You won! Congrats!\n\n".freeze
    LOSE_MSG = "You lost... Try again\n\n".freeze
  end
end
